#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: tiket 19 — Review dan peluncuran produksi
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

banner "Tiket 19: Review dan peluncuran produksi"
note "Prasyarat di luar wizard ini (jalankan dulu, terpisah, karena agent bisa"
note "menjalankannya sendiri): ponytail-review + code-review pada seluruh diff"
note "cabang, security-review, 'npm test' untuk acceptance 1-25/26-35 (termasuk"
note "perilaku bergantung waktu dengan jam yang disuntikkan)."
note "Batas keras: 17 September 2026 00.00 WIB (16 September 17.00 UTC)."

# ── Stage 1: Tinjau dan gabungkan cabang ───────────────────────────────────
stage "Tinjau & gabungkan cabang ke main"
say "dev-20260915 akan digabung ke main sebelum deploy produksi."
git -C "$(pwd)" fetch origin >/dev/null 2>&1 || warn "git fetch gagal; lanjut dengan salinan lokal"
say "Komit yang akan masuk ke main:"
git -C "$(pwd)" log main..dev-20260915 --oneline || true
if ! confirm "ponytail-review, code-review, dan security-review pada diff di atas sudah dijalankan dan temuannya diterapkan?"; then
  warn "berhenti di sini. Jalankan review lebih dulu, lalu ulangi wizard ini."
  exit 1
fi
if confirm "Gabungkan dev-20260915 ke main (squash, satu commit) dan push ke origin/main sekarang?"; then
  git checkout main
  git merge --squash dev-20260915
  git commit -m "feat: peluncuran tiket 19 — gabungan dev-20260915 (squash)"
  git push origin main
  say "Selesai. Cabang aktif sekarang: $(git branch --show-current)"
else
  warn "dilewati — pastikan kamu berada di cabang yang benar sebelum stage deploy."
fi

# ── Stage 2: tentang.md ────────────────────────────────────────────────────
stage "Konten /tentang (checklist B4)"
if [[ -f src/content/tentang.md ]]; then
  say "src/content/tentang.md sudah ada di repo."
else
  warn "src/content/tentang.md belum ada."
  say "Spesifikasi mengizinkan /tentang menampilkan \"Menyusul\" bila ini belum tersedia saat peluncuran; footer tetap tampil."
  confirm "Lanjut peluncuran tanpa tentang.md (tampil \"Menyusul\"), dan commit menyusul kapan pemilik produk siap?" \
    || { warn "berhenti di sini sampai tentang.md siap."; exit 1; }
fi

# ── Stage 3: Paket Workers ──────────────────────────────────────────────────
stage "Cek paket Workers (Free diizinkan, dengan risiko yang diketahui)"
warn "Keputusan diubah pasca-review: boleh lanjut di Workers Free. Ini melonggarkan tiket 06 keputusan 1"
warn "(\"Paket Free ditolak karena batas CPU 10 ms\"), mengikuti pola yang sudah dipakai tiket 09"
warn "(\"lanjutkan di Free, tetapi bila onboarding gagal karena batas CPU (galat 1102), aktifkan Paid dulu\")."
say "Batas CPU per invocation (dicek live ke docs Cloudflare): Free 10 ms, Paid 5 menit — berlaku untuk HTTP maupun Cron Trigger."
say "Operasi paling berisiko kena galat 1102 di Free:"
step "Sign-up/sign-in (hashing kata sandi Better Auth) — risiko sedang, per-request."
step "Cron Ekspor Harian 00.00 WIB (SHA-256 + ZIP seluruh berkas semua Bakal Calon sekaligus) — risiko TERTINGGI, satu invocation memproses banyak berkas."
open_url "https://dash.cloudflare.com/?to=/:account/billing/subscriptions"
step "Pilih akun pemegang zona kammi.id, lalu periksa Manage Account → Billing → Subscriptions (sekadar dicatat, bukan syarat lanjut)."
if confirm "Workers Paid aktif di akun ini?"; then
	say "Workers Paid aktif — batas 5 menit CPU, risiko 1102 di atas tidak relevan."
else
	warn "Lanjut di Workers Free. Pantau Workers Logs untuk galat 1102 selama peluncuran, terutama pada run Ekspor Harian pertama (malam ini, 00.00 WIB)."
	warn "Bila 1102 muncul: aktifkan Workers Paid di halaman yang baru dibuka, lalu jalankan ulang 'npm run deploy' — tidak perlu mengulang migrasi."
	confirm "Paham risiko di atas dan tetap lanjut di Free untuk sekarang?" || { warn "aktifkan Workers Paid dulu, lalu ulangi wizard ini."; exit 1; }
fi

# ── Stage 4: Migrasi D1 ────────────────────────────────────────────────────
stage "Terapkan migrasi baru ke D1 remote (bila ada)"
say "File migrasi saat ini:"
ls -1 migrations/ 2>/dev/null || warn "folder migrations/ tidak ditemukan"
note "0001_init.sql sudah diterapkan sejak tiket 09. Perubahan skema berikutnya wajib berupa file migrasi baru, bukan edit 0001_init.sql."
if confirm "Terapkan migrasi ke D1 remote sekarang (npx wrangler d1 migrations apply kpu-kammi-2026 --remote)?"; then
  npx wrangler d1 migrations apply kpu-kammi-2026 --remote
else
  warn "dilewati — pastikan tidak ada migrasi tertunda sebelum lanjut."
fi

# ── Stage 5: Deploy ulang ──────────────────────────────────────────────────
stage "Deploy ulang produksi"
say "Menjalankan npm run check (tsc + vite build + wrangler deploy --dry-run)."
npm run check
if confirm "npm run check lulus. Jalankan npm run deploy (npx wrangler deploy) sekarang?"; then
  npm run deploy
else
  warn "berhenti di sini — deploy belum dijalankan."
  exit 1
fi

# ── Stage 6: Verifikasi pasca-deploy ───────────────────────────────────────
stage "Verifikasi pasca-deploy (acceptance 35)"
say "Header respons kpu.kammi.id (harus TANPA x-middleware-rewrite):"
curl -sI https://kpu.kammi.id || warn "curl gagal — periksa DNS/Custom Domain"
say "Status r2.dev bucket kpu-kammi-2026-berkas (harus dinyatakan nonaktif):"
npx wrangler r2 bucket dev-url get kpu-kammi-2026-berkas || true
open_url "https://dash.cloudflare.com/?to=/:account/workers/services/view/kpu/production/settings/domains-routes"
step "Di Settings → Domains & Routes, pastikan workers.dev subdomain dan Preview URLs berstatus nonaktif, dan kpu.kammi.id terdaftar sebagai Custom Domain."
confirm "workers.dev, Preview URL, dan r2.dev tidak aktif; kpu.kammi.id dilayani Worker?" \
  || { warn "perbaiki dulu sebelum lanjut ke stage Admin."; exit 1; }

# ── Stage 7: Admin mengunggah Berkas Publik ────────────────────────────────
stage "Admin mengunggah Berkas Publik (checklist D18)"
warn "Teks Peraturan sekarang dibundel statis dari src/content/peraturan.md saat build (keputusan post-review: bukan lagi diedit Admin di runtime) — mengubahnya butuh commit + deploy ulang, bukan langkah di wizard ini."
say "Formulir A.1–A.6 tetap diunggah Admin sendiri di /admin/unggah-berkas, bukan Operator — kredensial Admin bersama tidak dipegang wizard ini."
open_url "https://kpu.kammi.id/admin/unggah-berkas"
step "Pemegang Admin login, lalu mengunggah PDF PKPU (kategori peraturan, dipakai KartuUnduhanBerkas di /peraturan) dan Formulir A.1–A.6 dalam PDF/DOCX (kategori formulir)."
note "Sebelum terunggah, /unduhan menampilkan \"Menyusul\" — ini tidak menghalangi Masa Pendaftaran dibuka, tapi harus tuntas sebelum 00.00 WIB."
confirm "Seluruh Formulir A.1–A.6 dan PDF PKPU terunggah di /admin/unggah-berkas?" || warn "belum tuntas — selesaikan sebelum pergantian tahap."

# ── Stage 8: Tidak ada akun uji ────────────────────────────────────────────
stage "Pastikan tidak ada akun uji di produksi"
say "Menampilkan baris tabel user (kecuali Admin) untuk diperiksa manual:"
npx wrangler d1 execute kpu-kammi-2026 --remote --command "SELECT id, email, role, createdAt FROM \"user\" WHERE role != 'admin'" || true
confirm "Tidak ada akun Bakal Calon uji di daftar di atas?" || { warn "hapus akun uji lewat tombol Hapus data akun sebelum lanjut."; exit 1; }

# ── Stage 9: Pengawasan pergantian tahap ───────────────────────────────────
stage "Pengawasan pergantian tahap (17 September 00.00–00.15 WIB)"
warn "JANGAN konfirmasi stage ini sebelum 17 September 2026 pukul 00.00 WIB. Boleh Ctrl-C dan jalankan ulang wizard ini nanti — stage 1–8 aman diulang."
open_url "https://kpu.kammi.id"
step "Pantau spanduk tahap di kpu.kammi.id sejak 00.00 WIB. Spanduk harus berganti dari Belum dibuka ke Masa Pendaftaran, dan tombol Daftar aktif."
confirm "Spanduk sudah Masa Pendaftaran dan tombol Daftar aktif (dalam jendela 00.00–00.15 WIB)?" \
  || { warn "belum berganti — cek Workers Logs / jam server sebelum melapor sebagai insiden."; exit 1; }

finish
say "Tiket 19 selesai. Perbarui checklist di .scratch/kpu-kammi-2026-website/issues/19-review-dan-peluncuran-produksi.md."
